## Gait Video study 
### Camera caibration 

In [1]:
import numpy as np
import cv2
import glob
import matplotlib.pyplot as plt

In [2]:
path = 'C:\\Users\\purpl\\Box\\Gait Video Project\\CameraCalibration\\1April\\mp4\\'

### Camera 1 - Side-look camera (_0)

In [201]:
# # Run only once to create the frames 
# #Convert videos to frames 
# vid_names = ['5_0_converted'] #'1_0_converted', '2_0_converted', '3_0_converted', '4_part1_0_converted', '4_part2_0_converted', 
# for vid_name in vid_names:
#     vidcap = cv2.VideoCapture(path+vid_name+'.mp4')
#     print (path+vid_name+'.mp4')
#     success,image = vidcap.read()
#     print (success)
# #     print (image)
#     count = 0
#     while success:
# #         print (path+'..\\frames\\vid_name_frame'+str(count)+'.jpg')
#         cv2.imwrite(path+'..\\frames\\sidelook\\'+vid_name+str(count)+'.jpg', image)     # save frame as JPEG file      
#         success,image = vidcap.read()
# #         print('Read a new frame: ', success)
#         count += 1
# #     break

In [202]:
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
# objp = np.zeros((4*6,3), np.float32)
# objp[:,:2] = np.mgrid[0:6,0:4].T.reshape(-1,2)
# objp[:, 0] = objp[:, 0]*3.5 + 3.5
# objp[:, 1] = objp[:, 1]*3.5 + 153.5

objp = np.zeros((4*6,3), np.float32)
objp[:,:2] = np.mgrid[0:4,0:6].transpose(1, 2, 0).reshape(-1,2)
objp[:, 0] = objp[:, 0]*3.5 + 57.5
objp[:, 1] = objp[:, 1]*3.5 + 150
objp[:, 2] = 0

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob(path+'..\\frames\\sidelook\\select4\\*.jpg')

In [203]:
print (objp)

[[ 57.5 150.    0. ]
 [ 57.5 153.5   0. ]
 [ 57.5 157.    0. ]
 [ 57.5 160.5   0. ]
 [ 57.5 164.    0. ]
 [ 57.5 167.5   0. ]
 [ 61.  150.    0. ]
 [ 61.  153.5   0. ]
 [ 61.  157.    0. ]
 [ 61.  160.5   0. ]
 [ 61.  164.    0. ]
 [ 61.  167.5   0. ]
 [ 64.5 150.    0. ]
 [ 64.5 153.5   0. ]
 [ 64.5 157.    0. ]
 [ 64.5 160.5   0. ]
 [ 64.5 164.    0. ]
 [ 64.5 167.5   0. ]
 [ 68.  150.    0. ]
 [ 68.  153.5   0. ]
 [ 68.  157.    0. ]
 [ 68.  160.5   0. ]
 [ 68.  164.    0. ]
 [ 68.  167.5   0. ]]


In [204]:
len(images)

11

In [ ]:
for fname in images: #35 selected images in total
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (6,4),None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        print (fname)
        fig = plt.figure(figsize=(10, 10))
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (6,4), corners2,ret)
        print (corners2)
        plt.imshow(img)
        fig.savefig(fname[:-4]+'_calibrate.png', dpi = 300, bbox_inches='tight', pad_inches=0)
#         plt.close()

In [206]:
len(objpoints), len(imgpoints)

(11, 11)

In [207]:
imgpoints

[array([[[350.68048 ,  41.90652 ]],
 
        [[351.35928 ,  54.59489 ]],
 
        [[351.63745 ,  68.26323 ]],
 
        [[352.10672 ,  81.32198 ]],
 
        [[352.44565 ,  94.59104 ]],
 
        [[353.02795 , 108.41958 ]],
 
        [[337.21936 ,  42.251587]],
 
        [[337.08026 ,  55.43844 ]],
 
        [[337.59116 ,  68.62457 ]],
 
        [[337.9561  ,  82.211494]],
 
        [[338.33243 ,  95.38585 ]],
 
        [[338.58978 , 108.80559 ]],
 
        [[322.7453  ,  42.739082]],
 
        [[323.28757 ,  56.127865]],
 
        [[323.5158  ,  69.16539 ]],
 
        [[323.8352  ,  82.58015 ]],
 
        [[324.09567 ,  95.83426 ]],
 
        [[324.57748 , 109.26861 ]],
 
        [[309.07034 ,  43.32503 ]],
 
        [[309.21265 ,  56.433765]],
 
        [[309.50784 ,  69.40282 ]],
 
        [[309.72168 ,  82.737114]],
 
        [[309.8971  ,  96.36177 ]],
 
        [[310.3031  , 109.704834]]], dtype=float32),
 array([[[265.61664 ,  94.2631  ]],
 
        [[278.84134 ,  94.147446]],

### Computing the intrinsic camera parameters (camera matrix and distortion matrix)

In [208]:
objpoints

[array([[ 57.5, 150. ,   0. ],
        [ 57.5, 153.5,   0. ],
        [ 57.5, 157. ,   0. ],
        [ 57.5, 160.5,   0. ],
        [ 57.5, 164. ,   0. ],
        [ 57.5, 167.5,   0. ],
        [ 61. , 150. ,   0. ],
        [ 61. , 153.5,   0. ],
        [ 61. , 157. ,   0. ],
        [ 61. , 160.5,   0. ],
        [ 61. , 164. ,   0. ],
        [ 61. , 167.5,   0. ],
        [ 64.5, 150. ,   0. ],
        [ 64.5, 153.5,   0. ],
        [ 64.5, 157. ,   0. ],
        [ 64.5, 160.5,   0. ],
        [ 64.5, 164. ,   0. ],
        [ 64.5, 167.5,   0. ],
        [ 68. , 150. ,   0. ],
        [ 68. , 153.5,   0. ],
        [ 68. , 157. ,   0. ],
        [ 68. , 160.5,   0. ],
        [ 68. , 164. ,   0. ],
        [ 68. , 167.5,   0. ]], dtype=float32),
 array([[ 57.5, 150. ,   0. ],
        [ 57.5, 153.5,   0. ],
        [ 57.5, 157. ,   0. ],
        [ 57.5, 160.5,   0. ],
        [ 57.5, 164. ,   0. ],
        [ 57.5, 167.5,   0. ],
        [ 61. , 150. ,   0. ],
        [ 61. , 153.5,

In [209]:
#Calculating the Camera matrix and Distortion matrix 
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

# # #Saving as .npy files 
# np.save(path+'..\\frames\\sidelook\\calibrate\\sidelook_camera_matrix', mtx)
# np.save(path+'..\\frames\\sidelook\\calibrate\\sidelook_distortion_matrix', dist)


In [186]:
# Load previously saved data
# sidelook_mtx = np.load(path+'..\\frames\\sidelook\\calibrate\\sidelook_camera_matrix.npy')
# sidelook_dist = np.load(path+'..\\frames\\sidelook\\calibrate\\sidelook_distortion_matrix.npy')

In [133]:
sidelook_mtx, sidelook_dist

NameError: name 'sidelook_mtx' is not defined

In [210]:
mtx, dist

(array([[1.12162880e+03, 0.00000000e+00, 3.15949830e+02],
        [0.00000000e+00, 1.69676687e+03, 2.38433315e+02],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]),
 array([[-9.81094785e+00,  3.07410723e+02, -4.77409062e-01,
          1.25709757e-01,  7.37722582e+00]]))

In [211]:
#Re-projection error gives a good estimation of just how exact is the found parameters. 
#This should be as close to zero as possible.
mean_error = 0
for i in range(len(objpoints)):
    imgpoints2, _ = cv2.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
    error = cv2.norm(imgpoints[i],imgpoints2, cv2.NORM_L2)/len(imgpoints2)
    print(error)
    mean_error += error

print ("total error: ", mean_error/len(objpoints))

0.04521032724695514
0.5336864198917476
0.757832252069258
0.7793559776090316
0.050864259737455404
0.0786880640425937
0.07698309664911072
0.07734097415438616
0.07544352521217165
0.04437110863674481
0.08427465508905863
total error:  0.23673187821259212


### Computing the extrinsic camera parameters (rotation and translation matrix)

In [212]:
def draw(img, corners, imgpts):
    corner = tuple(corners[0].ravel())
    img = cv2.line(img, corner, tuple(imgpts[0].ravel()), (255,0,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[1].ravel()), (0,255,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[2].ravel()), (0,0,255), 5)
    return img

In [213]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((24, 3), np.float32)
objp[:,:2] = np.mgrid[0:4,0:6].transpose(1, 2, 0).reshape(-1,2)
objp[:, 0] = objp[:, 0]*3.5 + 59
objp[:, 1] = objp[:, 1]*3.5 + 150
objp[:, 2] = 7

corners = np.zeros((12, 2), np.float32)

# axis = np.float32([[3,0,0], [0,3,0], [0,0,-3]]).reshape(-1,3)
axis = np.float32([[ 59+14, 150, 7], [ 59, 150+14, 7], [59, 150, 7-14]]).reshape(-1,3) #3 boxes each of 3.5*3.5
#zeros for x: 66, zero for y: 150, zero for z: 7 but block size is 3.5 ; 
#so (3, 0, 0) = (14, 164, 0); (0, 3, 0) = (3.5, 153.5, 0); (0, 0, -3) = (3.5, 164, -10.5)

In [219]:
#From the 2D green object 
objp = np.zeros((12, 3), np.float32)
corners = np.zeros((12, 2), np.float32)
objp[0] = [0, 150, 0]
corners[0] = [300, 17]

objp[1] = [0, 170, 0]
corners[1] = [361, 18]

objp[2] = [20, 150, 0]
corners[2] = [300, 61]

objp[3] = [20, 170, 0]
corners[3] = [365, 59]

#From the 2D green object on the other side 
objp[4] = [87, 150, 0]
corners[4] = [300, 242]

objp[5] = [87, 170, 0]
corners[5] = [382, 240]

objp[6] = [67, 170, 0]
corners[6] = [375, 175]

objp[7] = [67, 150, 0]
corners[7] = [298, 177]

# From the 3D green object 
objp[8] = [87, 150, 25]
corners[8] = [292, 171]

objp[9] = [87, 170, 25]
corners[9] = [392, 168]

objp[10] = [67, 170, 25]
corners[10] = [383, 99]

objp[11] = [67, 150, 25]
corners[11] = [292, 101]

In [175]:
corners, objp

(array([[300.,  17.],
        [361.,  18.],
        [300.,  61.],
        [365.,  59.],
        [300., 242.],
        [382., 240.],
        [375., 175.],
        [298., 177.],
        [292., 171.],
        [392., 168.],
        [383.,  99.],
        [292., 101.]], dtype=float32),
 array([[  0., 150.,   0.],
        [  0., 170.,   0.],
        [ 20., 150.,   0.],
        [ 20., 170.,   0.],
        [ 87., 150.,   0.],
        [ 87., 170.,   0.],
        [ 67., 170.,   0.],
        [ 67., 150.,   0.],
        [ 87., 150.,  25.],
        [ 87., 170.,  25.],
        [ 67., 170.,  25.],
        [ 67., 150.,  25.]], dtype=float32))

In [214]:
images2 = glob.glob(path+'..\\frames\\sidelook\\select3\\*.jpg')

In [215]:
images2

['C:\\Users\\purpl\\Box\\Gait Video Project\\CameraCalibration\\1April\\mp4\\..\\frames\\sidelook\\select3\\2_0_converted2971.jpg',
 'C:\\Users\\purpl\\Box\\Gait Video Project\\CameraCalibration\\1April\\mp4\\..\\frames\\sidelook\\select3\\2_0_converted3150.jpg',
 'C:\\Users\\purpl\\Box\\Gait Video Project\\CameraCalibration\\1April\\mp4\\..\\frames\\sidelook\\select3\\2_0_converted3300.jpg',
 'C:\\Users\\purpl\\Box\\Gait Video Project\\CameraCalibration\\1April\\mp4\\..\\frames\\sidelook\\select3\\2_0_converted3510.jpg',
 'C:\\Users\\purpl\\Box\\Gait Video Project\\CameraCalibration\\1April\\mp4\\..\\frames\\sidelook\\select3\\2_0_converted3691.jpg',
 'C:\\Users\\purpl\\Box\\Gait Video Project\\CameraCalibration\\1April\\mp4\\..\\frames\\sidelook\\select3\\2_0_converted3861.jpg',
 'C:\\Users\\purpl\\Box\\Gait Video Project\\CameraCalibration\\1April\\mp4\\..\\frames\\sidelook\\select3\\2_0_converted3871.jpg']

In [216]:
mtx, dist

(array([[1.12162880e+03, 0.00000000e+00, 3.15949830e+02],
        [0.00000000e+00, 1.69676687e+03, 2.38433315e+02],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]),
 array([[-9.81094785e+00,  3.07410723e+02, -4.77409062e-01,
          1.25709757e-01,  7.37722582e+00]]))

In [ ]:
for fname in images2:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, (6,4),None)
#     print (corners)

    if ret == True:
        plt.figure()
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
#         print ('corners2', corners2)
        # Find the rotation and translation vectors.
        print (corners2, objp)
        _, rvecs, tvecs, inliers = cv2.solvePnPRansac(objp, corners2, mtx, dist)
        print (rvecs, tvecs)
        #Post processing to check 
        rotM = cv2.Rodrigues(rvecs)[0]
#         print (rotM)
        cameraPosition = -np.matrix(rotM).T * np.matrix(tvecs)
        print ('Camera Position', cameraPosition)
#         print ('inliers', inliers)

        # project 3D points to image plane
        imgpts, jac = cv2.projectPoints(axis, rvecs, tvecs, mtx, dist)
#         print(img)
#         print (corners2)
#         print ('img', imgpts)
#         print ('axis', axis)
        
        img = draw(img,corners2,imgpts)
        plt.imshow(img)
        plt.savefig(fname[:-4]+'_axis.png', dpi = 300, bbox_inches='tight', pad_inches=0)
        #plt.close()

In [220]:
_, rvecs, tvecs = cv2.solvePnP(objp, corners, mtx, dist)
print (rvecs, tvecs)
#Post processing to check 
rotM = cv2.Rodrigues(rvecs)[0]
#         print (rotM)
cameraPosition = -np.matrix(rotM).T * np.matrix(tvecs)
print ('Camera Position', cameraPosition)

[[ 1.73841189]
 [ 1.68151779]
 [-0.75697803]] [[-155.02367019]
 [ -51.94995631]
 [ 445.79482082]]
Camera Position [[374.889755  ]
 [140.31039594]
 [255.41108617]]


In [999]:
# #Saving as .npy files 
np.save(path+'..\\frames\\sidelook\\calibrate\\sidelook_rotation_matrix', rvecs)
np.save(path+'..\\frames\\sidelook\\calibrate\\sidelook_translation_matrix', tvecs)


In [82]:
# Load previously saved data
sidelook_rvecs = np.load(path+'..\\frames\\sidelook\\calibrate\\sidelook_rotation_matrix.npy')
sidelook_tvecs = np.load(path+'..\\frames\\sidelook\\calibrate\\sidelook_translation_matrix.npy')

In [6]:
print ('Computed rotation vector', sidelook_rvecs)
print ('Computed translation vector', sidelook_tvecs)

Computed rotation vector [[ 2.04933399]
 [ 2.01845012]
 [-0.45984963]]
Computed translation vector [[-152.59950346]
 [ -79.890171  ]
 [ 121.21852086]]


In [7]:
#Post processing to check 
rotM = cv2.Rodrigues(sidelook_rvecs)[0]
print (rotM)
cameraPosition = -np.matrix(rotM).T * np.matrix(sidelook_tvecs)
print (cameraPosition)

[[ 0.00302692  0.99805993 -0.06218696]
 [ 0.92650382 -0.02619853 -0.37537223]
 [-0.37627319 -0.05648023 -0.92478564]]
[[120.09173368]
 [157.05689452]
 [ 72.6228963 ]]


In [9]:
sidelook_mtx

array([[333.99061135,   0.        , 307.68583952],
       [  0.        , 342.21519289, 248.6607367 ],
       [  0.        ,   0.        ,   1.        ]])

In [92]:
w = 640
h = 480
col, row = 292., 172 #300, 17 # 292., 172.  #293, 102 #122.747635  #292.234, 120 #306.29224, 121.75887#292.234, 122.80032 #292.234, 20# 306.29224, 121.75887 #
u=col-w/2
v=h/2-row
p = np.matmul(np.linalg.pinv(sidelook_mtx), np.array([col, row, 1]))
print (p.reshape(-1,1))
p1 = p*[0.15*sidelook_mtx[0, 0], 0.2*sidelook_mtx[1, 1], 0.15*sidelook_mtx[0, 0]] #At height 25
#constant = 55 at height 25
# p1 = 55*p #At height 25
p2 = p*[0.33*sidelook_mtx[0, 0], 0.33*sidelook_mtx[1, 1], 0.33*sidelook_mtx[0, 0]] #At height 0
#constant = 109 at height 0 
# p2 = 109*p
print (p1)

[[-0.04696491]
 [-0.22401325]
 [ 1.        ]]
[ -2.35287593 -15.33214734  50.0985917 ]


In [93]:
scale_z_0_on_treadmill = 37 + 72.6 #treadmill_height + camera's height 
scale_z_25_on_treadmill = 37 + 72.6 - 25 

In [94]:
scale_z_0_on_treadmill, scale_z_25_on_treadmill

(109.6, 84.6)

In [95]:
sidelook_mtx

array([[333.99061135,   0.        , 307.68583952],
       [  0.        , 342.21519289, 248.6607367 ],
       [  0.        ,   0.        ,   1.        ]])

In [96]:
p.T

array([-0.04696491, -0.22401325,  1.        ])

In [97]:
np.matmul(np.matrix(rotM).T, (p.reshape(-1,1) - np.matrix(sidelook_tvecs)))

matrix([[119.5077692 ],
        [156.95940931],
        [ 71.78511962]])

In [98]:
np.matmul(np.matrix(rotM).T, (p1.reshape(-1,1) - np.matrix(sidelook_tvecs)))

matrix([[ 87.02856186],
        [152.28068295],
        [ 32.19401887]])

In [99]:
np.matmul(np.matrix(rotM).T, (p2.reshape(-1,1) - np.matrix(sidelook_tvecs)))

matrix([[ 55.16566685],
        [146.32830518],
        [-19.48602832]])

In [1121]:
np.matmul(np.matrix(rotM).T, (55*p.reshape(-1,1) - np.matrix(sidelook_tvecs)))


matrix([[ 87.82528051],
        [151.86377426],
        [ 26.59526726]])

In [20]:
np.matmul(np.matrix(rotM).T, (55*p.reshape(-1,1) - np.matrix(sidelook_tvecs)))


matrix([[ 87.9736875 ],
        [151.69520789],
        [ 26.545179  ]])

In [1124]:
87.97-87.82

0.15000000000000568

### Camera 2 - Front-look camera (_1)

In [3]:
#Run only once to create the frames 
# #Convert videos to frames 
# vid_names = ['5_1_converted'] #'1_1_converted', '2_1_converted', '3_1_converted', '4_part1_1_converted', '4_part2_1_converted',
# for vid_name in vid_names:
#     vidcap = cv2.VideoCapture(path+vid_name+'.mp4')
# #     print (path+vid_name+'.mp4')
#     success,image = vidcap.read()
# #     print (image)
#     count = 0
#     while success:
# #         print (path+'..\\frames\\vid_name_frame'+str(count)+'.jpg')
#         cv2.imwrite(path+'..\\frames\\frontlook\\'+vid_name+str(count)+'.jpg', image)     # save frame as JPEG file      
#         success,image = vidcap.read()
# #         print('Read a new frame: ', success)
#         count += 1
# #     break

In [13]:
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
# objp = np.zeros((4*6,3), np.float32)
# objp[:,:2] = np.mgrid[0:6,0:4].T.reshape(-1,2)
# objp[:, 0] = objp[:, 0]*3.5 + 3.5
# objp[:, 1] = objp[:, 1]*3.5 + 153.5

objp_front = np.zeros((4*6,3), np.float32)
objp_front[:,0:2] = np.mgrid[0:4,0:6].transpose(1, 2, 0).reshape(-1,2)
objp_front[:, 0] = 57.5 - objp_front[:, 0]*3.5 
objp_front[:, 1] = 21 + objp_front[:, 1]*3.5
objp_front[:, 2] = 0

# Arrays to store object points and image points from all the images.
objpoints_front = [] # 3d point in real world space
imgpoints_front = [] # 2d points in image plane.

images_front = glob.glob(path+'..\\frames\\frontlook\\select\\*.jpg')

In [14]:
print (objp_front)

[[57.5 21.   0. ]
 [57.5 24.5  0. ]
 [57.5 28.   0. ]
 [57.5 31.5  0. ]
 [57.5 35.   0. ]
 [57.5 38.5  0. ]
 [54.  21.   0. ]
 [54.  24.5  0. ]
 [54.  28.   0. ]
 [54.  31.5  0. ]
 [54.  35.   0. ]
 [54.  38.5  0. ]
 [50.5 21.   0. ]
 [50.5 24.5  0. ]
 [50.5 28.   0. ]
 [50.5 31.5  0. ]
 [50.5 35.   0. ]
 [50.5 38.5  0. ]
 [47.  21.   0. ]
 [47.  24.5  0. ]
 [47.  28.   0. ]
 [47.  31.5  0. ]
 [47.  35.   0. ]
 [47.  38.5  0. ]]


In [15]:
len(images_front)

34

In [ ]:
for fname in images_front: #35 selected images in total
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (6,4),None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        print (fname)
        fig = plt.figure(figsize=(10, 10))
        objpoints_front.append(objp_front)

        corners2 = cv2.cornerSubPix(gray,corners,(8,8),(-1,-1),criteria)
        imgpoints_front.append(corners2)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (6,4), corners2,ret)
        print (corners2)
        plt.imshow(img)
        fig.savefig(fname[:-4]+'_calibrate.png', dpi = 300, bbox_inches='tight', pad_inches=0)
#         plt.close()

In [17]:
len(objpoints_front), len(imgpoints_front)

(33, 33)

In [18]:
imgpoints_front

[array([[[384.62833, 247.58754]],
 
        [[383.76544, 240.50607]],
 
        [[388.57196, 233.43639]],
 
        [[383.65543, 225.75505]],
 
        [[384.3295 , 218.51537]],
 
        [[384.3295 , 218.51537]],
 
        [[388.43365, 248.09923]],
 
        [[388.53992, 241.12018]],
 
        [[388.60672, 233.43051]],
 
        [[388.6653 , 226.44693]],
 
        [[388.6416 , 218.80394]],
 
        [[388.63953, 218.80371]],
 
        [[394.764  , 248.67018]],
 
        [[394.849  , 241.82927]],
 
        [[394.8212 , 233.71461]],
 
        [[394.68896, 226.57936]],
 
        [[395.12585, 219.25024]],
 
        [[395.1232 , 219.25049]],
 
        [[394.7655 , 248.67024]],
 
        [[399.3678 , 242.2748 ]],
 
        [[398.31454, 234.18867]],
 
        [[398.5522 , 226.8815 ]],
 
        [[397.0872 , 219.42369]],
 
        [[397.08722, 219.4237 ]]], dtype=float32),
 array([[[404.88327, 288.2597 ]],
 
        [[404.93222, 278.6241 ]],
 
        [[404.76828, 268.91425]],
 
        [[404

### Computing the intrinsic camera parameters (camera matrix and distortion matrix)

In [19]:
objpoints_front

[array([[57.5, 21. ,  0. ],
        [57.5, 24.5,  0. ],
        [57.5, 28. ,  0. ],
        [57.5, 31.5,  0. ],
        [57.5, 35. ,  0. ],
        [57.5, 38.5,  0. ],
        [54. , 21. ,  0. ],
        [54. , 24.5,  0. ],
        [54. , 28. ,  0. ],
        [54. , 31.5,  0. ],
        [54. , 35. ,  0. ],
        [54. , 38.5,  0. ],
        [50.5, 21. ,  0. ],
        [50.5, 24.5,  0. ],
        [50.5, 28. ,  0. ],
        [50.5, 31.5,  0. ],
        [50.5, 35. ,  0. ],
        [50.5, 38.5,  0. ],
        [47. , 21. ,  0. ],
        [47. , 24.5,  0. ],
        [47. , 28. ,  0. ],
        [47. , 31.5,  0. ],
        [47. , 35. ,  0. ],
        [47. , 38.5,  0. ]], dtype=float32),
 array([[57.5, 21. ,  0. ],
        [57.5, 24.5,  0. ],
        [57.5, 28. ,  0. ],
        [57.5, 31.5,  0. ],
        [57.5, 35. ,  0. ],
        [57.5, 38.5,  0. ],
        [54. , 21. ,  0. ],
        [54. , 24.5,  0. ],
        [54. , 28. ,  0. ],
        [54. , 31.5,  0. ],
        [54. , 35. ,  0. ],
   

In [20]:
gray.shape[::-1]

(800, 448)

In [21]:
# objpoints_frontg the Camera matrix and Distortion matrix 
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints_front, imgpoints_front, gray.shape[::-1],None,None)

# #Saving as .npy files 
np.save(path+'..\\frames\\frontlook\\calibrate\\frontlook_camera_matrix', mtx)
np.save(path+'..\\frames\\frontlook\\calibrate\\frontlook_distortion_matrix', dist)


In [22]:
# # Load previously saved data
frontlook_mtx = np.load(path+'..\\frames\\frontlook\\calibrate\\frontlook_camera_matrix.npy')
frontlook_dist = np.load(path+'..\\frames\\frontlook\\calibrate\\frontlook_distortion_matrix.npy')

In [23]:
frontlook_mtx, frontlook_dist

(array([[140.65857324,   0.        , 418.39876946],
        [  0.        , 134.09532584, 182.26565566],
        [  0.        ,   0.        ,   1.        ]]),
 array([[ 0.00561822, -0.02260983,  0.04406003, -0.00033956,  0.00693043]]))

In [24]:
mtx, dist

(array([[140.65857324,   0.        , 418.39876946],
        [  0.        , 134.09532584, 182.26565566],
        [  0.        ,   0.        ,   1.        ]]),
 array([[ 0.00561822, -0.02260983,  0.04406003, -0.00033956,  0.00693043]]))

In [25]:
#Re-projection error gives a good estimation of just how exact is the found parameters. 
#This should be as close to zero as possible.
mean_error = 0
for i in range(len(objpoints_front)):
    imgpoints2_front, _ = cv2.projectPoints(objpoints_front[i], rvecs[i], tvecs[i], frontlook_mtx, frontlook_dist)
    error = cv2.norm(imgpoints_front[i],imgpoints2_front, cv2.NORM_L2)/len(imgpoints2_front)
    print(error)
    mean_error += error

print ("total error: ", mean_error/len(objpoints_front))

0.4676276433744291
0.022644613079375635
0.03136911036288309
0.025496649836207873
0.04064325251975112
0.02583851194587858
0.029780104898008256
0.032187173147357466
0.03253174434484473
0.032151890132287045
0.03624723305488974
0.03342801701919698
0.026863676500292533
0.019189007878025074
0.025902791847547346
0.025908405638159826
0.024461202840572172
0.0183692718484751
0.02137056213821524
0.02633668901500007
0.019812598712363235
0.024813936918281782
0.022240542640095142
0.023913838147782984
0.0369713971759859
0.029848279622084025
0.029307863449376224
0.03145340787353972
0.04276867951781435
0.9390332154097694
1.0673607674142678
1.0251775825352463
0.7885404469900755
total error:  0.15392697296448726


### Computing the extrinsic camera parameters (rotation and translation matrix)

In [30]:
def draw(img, corners, imgpts):
    corner = tuple(corners[0].ravel())
    img = cv2.line(img, corner, tuple(imgpts[0].ravel()), (255,0,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[1].ravel()), (0,255,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[2].ravel()), (0,0,255), 5)
    return img

In [34]:
np.mgrid[0:4,0:6].transpose(1, 2, 0).reshape(-1,2), objp_front[:,:2]

(array([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=float32))

In [26]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp_front = np.zeros((24, 3), np.float32)
objp_front[:,0:2] = np.mgrid[0:4,0:6].transpose(1, 2, 0).reshape(-1,2)
objp_front[:, 0] = objp_front[:, 0]*3.5 + 30
objp_front[:, 1] = 30 - objp_front[:, 1]*3.5
objp_front[:, 2] = 250

corners_front = np.zeros((12, 2), np.float32)

# axis = np.float32([[3,0,0], [0,3,0], [0,0,-3]]).reshape(-1,3)
axis = np.float32([[ 30+14, 30, 250], [ 30, 30-14, 250], [30, 30, 250+14]]).reshape(-1,3) #3 boxes each of 3.5*3.5
#zeros for x: 66, zero for y: 150, zero for z: 7 but block size is 3.5 ; 
#so (3, 0, 0) = (14, 164, 0); (0, 3, 0) = (3.5, 153.5, 0); (0, 0, -3) = (3.5, 164, -10.5)

In [37]:
#From the 2D green object 
objp_front = np.zeros((12, 3), np.float32)
corners_front = np.zeros((12, 2), np.float32)

objp_front[0] = [0, 150, 0]
corners_front[0] = [486, 272]

objp_front[1] = [0, 170, 0]
corners_front[1] = [494, 282]

objp_front[2] = [20, 150, 0]
corners_front[2] = [448, 272]

objp_front[3] = [20, 170, 0]
corners_front[3] = [454, 284]

#From the 2D green object on the other side 
objp_front[4] = [87, 150, 0]
corners_front[4] = [321, 275]

objp_front[5] = [87, 170, 0]
corners_front[5] = [317, 287]

objp_front[6] = [67, 170, 0]
corners_front[6] = [357, 285]

objp_front[7] = [67, 150, 0]
corners_front[7] = [360, 273]

# From the 3D green object 
objp_front[8] = [87, 150, 25]
corners_front[8] = [317, 228]

objp_front[9] = [87, 170, 25]
corners_front[9] = [314, 235]

objp_front[10] = [67, 170, 25]
corners_front[10] = [358, 235]

objp_front[11] = [67, 150, 25]
corners_front[11] = [357, 227]

In [38]:
corners_front, objp_front

(array([[486., 272.],
        [494., 282.],
        [448., 272.],
        [454., 284.],
        [321., 275.],
        [317., 287.],
        [357., 285.],
        [360., 273.],
        [317., 228.],
        [314., 235.],
        [358., 235.],
        [357., 227.]], dtype=float32),
 array([[  0.,   0., 150.],
        [  0.,   0., 170.],
        [ 20.,   0., 150.],
        [ 20.,   0., 170.],
        [ 87.,   0., 150.],
        [ 87.,   0., 170.],
        [ 67.,   0., 170.],
        [ 67.,   0., 150.],
        [ 87.,  25., 150.],
        [ 87.,  25., 170.],
        [ 67.,  25., 170.],
        [ 67.,  25., 150.]], dtype=float32))

In [28]:
images2 = glob.glob(path+'..\\frames\\frontlook\\select3\\*.jpg')

In [ ]:
for fname in images2:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, (6,4),None)
#     print (corners)

    if ret == True:
        plt.figure()
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
#         print ('corners2', corners2)
        # Find the rotation and translation vectors.
#         print (corners2, objp)
        _, rvecs, tvecs, inliers = cv2.solvePnPRansac(objp_front, corners2, frontlook_mtx, frontlook_dist)
        print (rvecs, tvecs)
        #Post processing to check 
        rotM = cv2.Rodrigues(rvecs)[0]
#         print (rotM)
        cameraPosition = -np.matrix(rotM).T * np.matrix(tvecs)
        print ('Camera Position', cameraPosition)
#         print ('inliers', inliers)

        # project 3D points to image plane
        imgpts, jac = cv2.projectPoints(axis, rvecs, tvecs, frontlook_mtx, frontlook_dist)
#         print(img)
#         print (corners2)
#         print ('img', imgpts)
#         print ('axis', axis)
        
        img = draw(img,corners2,imgpts)
        plt.imshow(img)
        plt.savefig(fname[:-4]+'_axis.png', dpi = 300, bbox_inches='tight', pad_inches=0)
        #plt.close()

In [39]:
_, rvecs, tvecs = cv2.solvePnP(objp_front, corners_front, frontlook_mtx, frontlook_dist)
print (rvecs, tvecs)
#Post processing to check 
rotM = cv2.Rodrigues(rvecs)[0]
#         print (rotM)
cameraPosition_front = -np.matrix(rotM).T * np.matrix(tvecs)
print ('Camera Position', cameraPosition_front)

[[-0.25643402]
 [ 1.2302662 ]
 [ 2.8681538 ]] [[ 59.35189184]
 [-63.75851875]
 [-26.9132313 ]]
Camera Position [[ 50.90073997]
 [-20.35249975]
 [ 72.84921566]]


In [93]:
# #Saving as .npy files 
np.save(path+'..\\frames\\frontlook\\calibrate\\frontlook_rotation_matrix', rvecs)
np.save(path+'..\\frames\\frontlook\\calibrate\\frontlook_translation_matrix', tvecs)


In [95]:
# Load previously saved data
frontlook_rvecs = np.load(path+'..\\frames\\frontlook\\calibrate\\frontlook_rotation_matrix.npy')
frontlook_tvecs = np.load(path+'..\\frames\\frontlook\\calibrate\\frontlook_translation_matrix.npy')

In [96]:
print ('Computed rotation vector', frontlook_rvecs)
print ('Computed translation vector', frontlook_tvecs)

Computed rotation vector [[ 0.01034259]
 [ 2.39651751]
 [-2.00912523]]
Computed translation vector [[ 53.73060356]
 [ 23.15320698]
 [206.61731257]]


In [97]:
#Post processing to check 
rotM = cv2.Rodrigues(frontlook_rvecs)[0]
print (rotM)
cameraPosition_front = -np.matrix(rotM).T * np.matrix(frontlook_tvecs)
print (cameraPosition_front)

[[-0.99987595  0.01425232  0.00670542]
 [-0.00411532  0.17454189 -0.98464115]
 [-0.0152038  -0.9845466  -0.17446159]]
[[ 56.96058868]
 [198.6173815 ]
 [ 58.48409791]]


In [98]:
frontlook_mtx

array([[ 77.0573586 ,   0.        , 393.92446068],
       [  0.        ,  79.0755211 , 177.65831886],
       [  0.        ,   0.        ,   1.        ]])

In [181]:
w = 640
h = 480
col, row = 486., 272. #300, 17 # 292., 172.  #293, 102 #122.747635  #292.234, 120 #306.29224, 121.75887#292.234, 122.80032 #292.234, 20# 306.29224, 121.75887 #

# #From the 2D green object 
# objp_front[0] = [0, 150, 0]
# corners_front[0] = [486, 272]

# objp_front[1] = [0, 170, 0]
# corners_front[1] = [494, 282]

# objp_front[2] = [20, 150, 0]
# corners_front[2] = [448, 272]

# objp_front[3] = [20, 170, 0]
# corners_front[3] = [454, 284]

# #From the 2D green object on the other side 
# objp_front[4] = [87, 150, 0]
# corners_front[4] = [321, 275]

# objp_front[5] = [87, 170, 0]
# corners_front[5] = [317, 287]

# objp_front[6] = [67, 170, 0]
# corners_front[6] = [357, 285]

# objp_front[7] = [67, 150, 0]
# corners_front[7] = [360, 273]

# # From the 3D green object 
# objp_front[8] = [87, 150, 25]
# corners_front[8] = [317, 228]

# objp_front[9] = [87, 170, 25]
# corners_front[9] = [314, 235]

# objp_front[10] = [67, 170, 25]
# corners_front[10] = [358, 235]

# objp_front[11] = [67, 150, 25]
# corners_front[11] = [357, 227]

u=col-w/2
v=h/2-row
p = np.matmul(np.linalg.pinv(frontlook_mtx), np.array([col, row, 1]))
print (p.reshape(-1,1))
# p1 = p*[0.6*frontlook_mtx[0, 0], 0.15*frontlook_mtx[1, 1], 0.5*frontlook_mtx[0, 0]] #At height 25
#constant = 55 at height 25
p1 = 95*p #At height 25
p2 = p*[0.33*frontlook_mtx[0, 0], 0.33*frontlook_mtx[1, 1], 0.33*frontlook_mtx[0, 0]] #At height 0
#constant = 109 at height 0 
# p2 = 109*p
print (p1)

[[1.19489613]
 [1.19305798]
 [1.        ]]
[113.51513203 113.34050771  95.        ]


In [182]:
np.matmul(np.matrix(rotM).T, (p1.reshape(-1,1) - np.matrix(frontlook_tvecs)))

matrix([[-58.4512542 ],
        [126.48597535],
        [-68.9283138 ]])

In [166]:
scale_z_0_on_treadmill = 37 + 58.5 #treadmill_height + camera's height 
scale_z_25_on_treadmill = 37 + 58.5 - 25 

In [167]:
scale_z_0_on_treadmill, scale_z_25_on_treadmill

(95.5, 70.5)

In [117]:
sidelook_mtx

array([[103.16427404,   0.        , 395.79369152],
       [  0.        , 108.68485766, 216.97654797],
       [  0.        ,   0.        ,   1.        ]])

In [118]:
p.T

array([1.19489613, 1.19305798, 1.        ])

In [119]:
np.matmul(np.matrix(rotM).T, (p.reshape(-1,1) - np.matrix(frontlook_tvecs)))

matrix([[ 55.74572718],
        [197.85810354],
        [ 57.14291463]])

In [120]:
np.matmul(np.matrix(rotM).T, (p1.reshape(-1,1) - np.matrix(frontlook_tvecs)))

matrix([[-15.93110156],
        [153.06070393],
        [-21.98689896]])

In [121]:
np.matmul(np.matrix(rotM).T, (p2.reshape(-1,1) - np.matrix(frontlook_tvecs)))

matrix([[ 26.06469265],
        [179.44844226],
        [ 23.59687903]])

In [ ]:
np.matmul(np.matrix(rotM).T, (55*p.reshape(-1,1) - np.matrix(sidelook_tvecs)))


In [ ]:
np.matmul(np.matrix(rotM).T, (55*p.reshape(-1,1) - np.matrix(sidelook_tvecs)))


In [ ]:
87.97-87.82